### ISSUE TITLE
E-Mail Template Texts

### ISSUE THREAD

**Issue by MiniDigger** [HangarMC/HangarAuth#135]
need to find good texts for the emails:
https://github.com/HangarMC/HangarAuth/tree/master/docker/deployment/kratos/templates

**Comment by mrfloris** [comment]
```
Hey, welcome and nice to meet you,

This email was used to sign up for an account on {{ baseUrl }} please verify your profile and start enjoying PaperMC right away.

Getting started can sometimes be challenging but at PaperMC, just like starting a Minecraft server, we like to keep things hassle-free — that’s why we’ve made verifying your profile easy.

Tap the link below and be a part of a community of Minecraft enthousiasts who’ve decided to make most out of developing for and/or running servers:

<a href="{{ .VerificationURL }}">{{ .VerificationURL }}</a>


We can’t wait to see you,
The PaperMC team
```

Note: I know, lots of lovey-dovey talk, it can probably be cut in half and toned down a bit. But I left it in to give ideas.
Note: baseUrl is unknown to me, but added it as a reminder in case there it one - to use one. 

My point with the suggestion is to make it feel less like a 'developer email' response and a bit more 'end-user friendly' welcoming notice. While still remaining plain-text.

**Comment by mrfloris** [comment]
and for recovery, maybe something along the lines of..

```
subject: PaperMC Account Recovery

Hello, sorry to hear you are having issues with your account.

Please tap the below link to help recover access for the PaperMC account {{ .RecoveryEmailObfuscated }} (example: ****@example.com)

Here is your temporary link: {{ .RecoveryURL }}

If you don't recognise the PaperMC account {{ .RecoveryEmailObfuscated }}, you can remove your email address from that account: {{ .RecoveryEmailRemoveLink }}

Thanks,
The PaperMC team
```

**Comment by aurorasmiles** [comment]
I've noticed that even though the current templates are all formatted nicely, Thunderbird for me just throws everything into one line, so right now I just get
> Hi, Hello, Please click the below link to help recover access to your account. Here is your temporary link: https://hangar-auth.benndorf.dev/kratos/self-service/recovery?flow=* Thanks, The PaperMC team
