### ISSUE TITLE
Security key used for registration buggy

### ISSUE THREAD

**Issue by aurorasmiles** [HangarMC/HangarAuth#178]
- When using a security key for registration, that security key is not visible in your profile.
- If you try to add a new security key, but cancel that process, your initial security key gets removed/invalidated, causing you to potentially loose access
- If you add a the security key again the initial security key becomes visible as well. Removing either one of the security keys will cause them both to be removed

**Comment by MiniDigger** [comment]
passwordless sign up has been disabled until kratos gets more stable with that
