### ISSUE TITLE
The forgotten comma

### ISSUE THREAD

**Issue by mastermc05** [HangarMC/HangarAuth#186]
https://github.com/HangarMC/HangarAuth/blob/b8bb7510d385b0713669929fd1dd913c3e21b37d/docker/deployment/kratos/hooks/settings/after/profile.jsonnet#L3
there should be a comma
![image](https://user-images.githubusercontent.com/63639746/184515797-65c9d182-d2bb-4b79-818a-36e1dab84e35.png)

**Comment by MiniDigger** [comment]
fixed
