### ISSUE TITLE
Restrict username changing

### ISSUE THREAD

**Issue by kennytv** [HangarMC/HangarAuth#277]
Changing the username should be restricted to once per month (or even longer), or require mod approval - although I'd prefer the time option. Also see https://discord.com/channels/855123416889163777/859527399901626398/1056615488844738620

Showing a name history on the Hangar profile would also be good.

**Comment by MiniDigger** [comment]
https://github.com/HangarMC/Hangar/commit/aed7aa9cd470f769f47a0b7b356d7ca11c73d8be
