### ISSUE TITLE
Bug with alert email verify in settings page

### ISSUE THREAD

**Issue by EncryptSL** [HangarMC/HangarAuth#286]
Idk, if this knowledged issue but when someone have verified email, still is visible alert about not verified email, same after refresh.

![image](https://user-images.githubusercontent.com/9441083/223310471-32dc5ae7-9f8b-45aa-a4e2-6d64d8a768d9.png)

**Comment by MiniDigger** [comment]
cant repro, works fine for me, are you sure you actually verified your email by entering the code?

**Comment by EncryptSL** [comment]
Yep, i have verified email. Two times i verified email but this alert is showed again aftter i open page. 

Btw idk if this is showed too on another browser.
