### ISSUE TITLE
2FA QR code on profile should be blurred out by default to prevent accidental sharing

### ISSUE THREAD

**Issue by lokka30** [HangarMC/HangarAuth#288]
### Is your feature request related to a problem?

It's easy to accidentally share your 2FA QR code by taking a screenshot of your member settings page. Perhaps any sensitive information should be hidden by default so that it won't be accidentally shared.

### Describe the solution you'd like.

I think the 2FA QR code on members' member settings should be blurred out by default, which can be toggled via a button, switch, or some other input.

### Describe alternatives you've considered.

1. Moving sensitive member information into a sub-page - it likely requires more work.
2. Adding a callout or something onto the profile page informing users that there is sensitive information on their member settings page which should not be shared with anyone.

**Comment by MiniDigger** [comment]
reverted this again, no need to blur, the code is regenerated every time you open the settings and only actually used if verified, after that the code is never shown again
