### ISSUE TITLE
2FA Recovery Codes should require 2FA (re)entry to view

### ISSUE THREAD

**Issue by KairuByte** [HangarMC/HangarAuth#289]
Without this, a session hijack, or even just someone passing by an unlocked PC can gain access to the codes, effectively bypassing 2FA.

**Comment by kennytv** [comment]
It's always a freshly generated code that you need to verify using 2fa

**Comment by MiniDigger** [comment]
changing any setting requires a so called privileged session, which you enter by logging in with your 2fa method(s) of choice. however, that privileged session expires way quicker than your login session, prompting for relogin with your password.
