### ISSUE TITLE
Password change should require re-entering current password

### ISSUE THREAD

**Issue by KairuByte** [HangarMC/HangarAuth#291]
Similar to both #289 and #290, not requiring current password verification when changing passwords is a security risk. This opens accounts up to a session hijack resulting in a total loss of account access.

**Comment by MiniDigger** [comment]
changing any setting requires a so called privileged session, which you enter by logging in with your 2fa method(s) of choice. however, that privileged session expires way quicker than your login session, prompting for relogin with your password.
