### ISSUE TITLE
Email verification should not "dead end"

### ISSUE THREAD

**Issue by KairuByte** [HangarMC/HangarAuth#293]
When entering the verification process through the profile, you eventually reach a "dead end" where you have no direct way back to your profile and are forced to fumble your way back to hangar. Having a "back to profile" button, auto redirect, or even the normal hangar navbar at the top would be an easy solution for this.

**Comment by MiniDigger** [comment]
https://github.com/ory/kratos/pull/3090

**Comment by MiniDigger** [comment]
https://github.com/HangarMC/HangarAuth/pull/294
