### ISSUE TITLE
Allow option for signing with email

### ISSUE THREAD

**Issue by Chew** [HangarMC/HangarAuth#4]
It would be nicer (and more secure) to have an option to allow only signing in with an email, or allowing username and email. I don't want people guessing away at my password assuming they don't have my email and only username.

**Comment by Machine-Maker** [comment]
An option to sign in w/email? Wouldn't it have to be required? or else people could just still use your username. I'd be for changing the login to require email/password rather than username/password. But that would be for all users, not as an option.

**Comment by Chew** [comment]
Something like this, if possible.
![image](https://user-images.githubusercontent.com/8278263/102681155-c31edb80-4184-11eb-8c38-4b92ca845605.png)

**Comment by Machine-Maker** [comment]
Oh is that like a per-user setting?

**Comment by Chew** [comment]
Yes. I highly doubt most people would change it beyond all types allowed, but it is a cool step. Though with 2fa it kinda defeats the purpose a bit. I'd feel a bit more secure knowing they'd need my email even if they do have my password.

**Comment by Machine-Maker** [comment]
Is there a downside to just forcing everyone to log in w/their email?

**Comment by Chew** [comment]
Laziness. Actually, how do people sign up? It depends on how their password managers handle it. Mine stored email and password, so I have to switch it to the username. It should, at a minimum, allow email signins.

**Comment by Machine-Maker** [comment]
I mean most accounts I have only let you sign in w/email and password. But yes, if we don't force everyone to signin w/email + password, then allowing sign in with email/username + password, would be good.

**Comment by MiniDigger** [comment]
no longer relevant
