### ISSUE TITLE
support gifs as avatars

### ISSUE THREAD

**Issue by MiniDigger** [HangarMC/HangarAuth#6]
if you upload a gif, you get a 500 on a url like this https://hangar-auth.minidigger.me/avatar/Peaches_MLG?size=120x120

**Comment by Machine-Maker** [comment]
I think supporting gifs for pfp would be a cool "perk" right?

**Comment by MiniDigger** [comment]
There is a difference between gif and animated gif, but yeah, good idea.

**Comment by Machine-Maker** [comment]
yes, I meant animated ones.

**Comment by MiniDigger** [comment]
lets not for now
